from .xgboost_prompts import (
    XGB_SYSTEM_PROMPT, XGB_USER_TEMPLATE,
    XGB_TRAINING_TEMPLATE, XGB_FEW_SHOT_EXAMPLES
)
from .lstm_prompts import (
    LSTM_SYSTEM_PROMPT, LSTM_USER_TEMPLATE,
    LSTM_TRAINING_TEMPLATE, LSTM_COT_TEMPLATE
)
from .yolov8_prompts import (
    YOLO_SYSTEM_PROMPT, YOLO_USER_TEMPLATE,
    YOLO_ANNOTATION_TEMPLATE, YOLO_FEW_SHOT_EXAMPLES
)
from .fault_prompts import (
    FAULT_SYSTEM_PROMPT, FAULT_USER_TEMPLATE,
    FAULT_SYNTHETIC_PROMPT, FAULT_COT_TEMPLATE
)
from .orchestrator_prompts import (
    MASTER_SYSTEM_PROMPT, RECOMMENDATION_CHAIN_PROMPT
)
